from __future__ import annotations

from urllib.parse import quote_plus

from .models import Difficulty, Exercise, Target


def yt_search_url(query: str) -> str:
    return f"https://www.youtube.com/results?search_query={quote_plus(query)}"


EXERCISES: list[Exercise] = [
    Exercise(
        id="plank",
        name="플랭크",
        url=yt_search_url("플랭크 자세"),
        targets={Target.FULL_CORE},
        rep_type="seconds",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="팔꿈치 아래에 어깨를 두고, 엉덩이가 뜨거나 처지지 않게 유지.",
        caution="허리 통증이 있으면 시간을 줄이고 복압 유지에 집중.",
    ),
    Exercise(
        id="side_plank",
        name="사이드 플랭크",
        url=yt_search_url("사이드 플랭크 자세"),
        targets={Target.OBLIQUES},
        rep_type="seconds",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="어깨-골반-발이 일직선. 목 길게, 골반 떨어지지 않게.",
        caution="어깨가 아프면 팔꿈치 각도 조정 또는 짧게.",
    ),
    Exercise(
        id="dead_bug",
        name="데드버그",
        url=yt_search_url("데드버그 운동 자세"),
        targets={Target.FULL_CORE},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="허리를 바닥에 붙이고, 팔다리는 천천히 멀어지게.",
        caution="허리가 뜨면 가동범위를 줄이기.",
    ),
    Exercise(
        id="bird_dog",
        name="버드독",
        url=yt_search_url("버드독 운동 자세"),
        targets={Target.FULL_CORE},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="골반이 흔들리지 않게, 팔/다리를 길게 뻗었다가 복귀.",
        caution="손목이 불편하면 주먹 또는 팔꿈치 지지로 변형.",
    ),
    Exercise(
        id="crunch",
        name="크런치",
        url=yt_search_url("크런치 자세"),
        targets={Target.FULL_CORE, Target.LOWER_ABS},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="턱 당기고, 배의 힘으로 상체를 살짝만 말아 올리기.",
        caution="목에 힘이 들어가면 시선 고정/손 위치 조정.",
    ),
    Exercise(
        id="reverse_crunch",
        name="리버스 크런치",
        url=yt_search_url("리버스 크런치 자세"),
        targets={Target.LOWER_ABS},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.BEGINNER,
        form_tip="무릎을 가슴 쪽으로 끌어오며 꼬리뼈가 살짝 들리게.",
        caution="반동 금지. 허리가 뜨면 범위 축소.",
    ),
    Exercise(
        id="leg_raise",
        name="레그 레이즈",
        url=yt_search_url("레그 레이즈 자세"),
        targets={Target.LOWER_ABS},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="다리를 곧게, 천천히 올렸다 내리기. 허리 뜨지 않게.",
        caution="허리 뜨면 무릎 살짝 굽히거나 반복 수 감소.",
    ),
    Exercise(
        id="flutter_kick",
        name="플러터 킥",
        url=yt_search_url("플러터 킥 자세"),
        targets={Target.LOWER_ABS},
        rep_type="seconds",
        noise_level="quiet",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="허리 바닥 고정. 작은 범위로 리듬 있게 교차.",
        caution="허리 불편하면 다리 높이를 올려 부담 줄이기.",
    ),
    Exercise(
        id="russian_twist",
        name="러시안 트위스트",
        url=yt_search_url("러시안 트위스트 자세"),
        targets={Target.OBLIQUES},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="가슴 열고, 몸통 회전은 천천히. 허리는 길게.",
        caution="허리 비틀림 통증이 있으면 범위 축소 또는 발 고정.",
    ),
    Exercise(
        id="hip_dip",
        name="힙 딥",
        url=yt_search_url("힙 딥 운동 자세"),
        targets={Target.OBLIQUES},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="사이드 플랭크에서 골반을 아래로 내렸다가 끌어올리기.",
        caution="어깨 부담 시 정적 홀드로 대체.",
    ),
    Exercise(
        id="mountain_climber_low_impact",
        name="마운틴 클라이머(저충격)",
        url=yt_search_url("마운틴 클라이머 저충격 자세"),
        targets={Target.FULL_CORE},
        rep_type="seconds",
        noise_level="medium",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="발을 가볍게 디디며 무릎을 번갈아 당기기. 엉덩이 높이 유지.",
        caution="손목이 불편하면 상체를 높이거나 천천히 진행.",
    ),
    Exercise(
        id="shoulder_tap",
        name="숄더 탭",
        url=yt_search_url("숄더 탭 플랭크 자세"),
        targets={Target.FULL_CORE},
        rep_type="reps",
        noise_level="medium",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="플랭크 자세에서 골반 흔들림 최소화하며 어깨 터치.",
        caution="허리 흔들리면 무릎 플랭크로 낮추기.",
    ),
    Exercise(
        id="push_up",
        name="푸시업",
        url=yt_search_url("푸시업 자세"),
        targets={Target.FULL_CORE},
        rep_type="reps",
        noise_level="quiet",
        min_difficulty=Difficulty.INTERMEDIATE,
        form_tip="몸통 일직선 유지. 팔꿈치 45도. 가슴 바닥 쪽으로.",
        caution="손목 통증 시 그립 변경(보드/손잡이) 또는 무릎 대고.",
    ),
]

